/** Notes, Subject Areas, table color and transaction-scope analysis. */
(() => {
  'use strict';
  const E=window.ERDEditor,A=E.Advanced;
  function point(x,y){const r=workspace.getBoundingClientRect();return{x:Math.round((x-r.left-panX)/scale),y:Math.round((y-r.top-panY)/scale)}}
  function layers(){let g=document.getElementById('subject-area-layer');if(!g){g=document.createElement('div');g.id='subject-area-layer';canvasLayer.insertBefore(g,svgOverlay);}let n=document.getElementById('note-layer');if(!n){n=document.createElement('div');n.id='note-layer';canvasLayer.appendChild(n);}return{g,n};}

  function addNoteAt(x=innerWidth/2,y=innerHeight/2){const text=prompt('메모 내용');if(!text?.trim())return;const p=point(x,y);A.mutate('메모를 추가했습니다.',()=>{A.view().notes||=[];A.view().notes.push({id:A.uid('note'),text:text.trim(),x:p.x,y:p.y,color:'#fbbf24'});});}
  function editNote(id){const note=(A.view().notes||[]).find(n=>n.id===id);if(!note)return;const text=prompt('메모 내용',note.text);if(text===null)return;A.mutate('메모 수정',()=>note.text=text.trim());}
  function deleteNote(id){if(!confirm('메모를 삭제할까요?'))return;A.mutate('메모 삭제',()=>A.view().notes=(A.view().notes||[]).filter(n=>n.id!==id));}
  function renderNotes(){const{n}=layers();n.innerHTML='';(A.view()?.notes||[]).forEach(note=>{const el=document.createElement('div');el.className='erd-note';el.dataset.noteId=note.id;el.style.left=`${note.x}px`;el.style.top=`${note.y}px`;el.style.setProperty('--note-color',note.color||'#fbbf24');el.innerHTML=`<div class="erd-note-handle"><i class="fa-solid fa-note-sticky"></i> NOTE</div><div class="erd-note-text">${E.escapeHtml(note.text).replaceAll('\n','<br>')}</div>`;el.ondblclick=e=>{e.stopPropagation();editNote(note.id)};el.oncontextmenu=e=>{e.preventDefault();e.stopPropagation();if(confirm('확인: 삭제 / 취소: 편집'))deleteNote(note.id);else editNote(note.id)};el.querySelector('.erd-note-handle').onmousedown=e=>{e.preventDefault();e.stopPropagation();const before=E.snapshot(),sx=e.clientX,sy=e.clientY,ox=note.x,oy=note.y;const move=ev=>{note.x=ox+(ev.clientX-sx)/scale;note.y=oy+(ev.clientY-sy)/scale;el.style.left=`${note.x}px`;el.style.top=`${note.y}px`};const up=()=>{removeEventListener('mousemove',move);removeEventListener('mouseup',up);if(before!==E.snapshot()){E.pushUndo(before);E.persist();}};addEventListener('mousemove',move);addEventListener('mouseup',up)};n.appendChild(el);});}

  function createSubjectArea(){const ids=[...E.selectedIds];if(!ids.length)return alert('그룹으로 묶을 테이블을 선택하세요.');const name=prompt('Subject Area 이름','Domain');if(!name?.trim())return;const color=prompt('테두리 색상','#8b5cf6')||'#8b5cf6';A.mutate('Subject Area 생성',()=>{A.view().groups||=[];A.view().groups.push({id:A.uid('group'),name:name.trim(),tableIds:ids,color});});}
  function deleteGroup(id){if(!confirm('Subject Area를 삭제할까요?'))return;A.mutate('Subject Area 삭제',()=>A.view().groups=(A.view().groups||[]).filter(g=>g.id!==id));}
  A.updateGroupBounds=()=>{(A.view()?.groups||[]).forEach(group=>{const el=document.querySelector(`.subject-area[data-group-id="${CSS.escape(group.id)}"]`);if(!el)return;const ts=group.tableIds.map(E.findTable).filter(Boolean);if(!ts.length){el.style.display='none';return;}const minX=Math.min(...ts.map(t=>t.x||0))-36,minY=Math.min(...ts.map(t=>t.y||0))-52,maxX=Math.max(...ts.map(t=>(t.x||0)+360))+36,maxY=Math.max(...ts.map(t=>(t.y||0)+58+(t.columns?.length||0)*34))+36;Object.assign(el.style,{left:`${minX}px`,top:`${minY}px`,width:`${maxX-minX}px`,height:`${maxY-minY}px`,display:''});});};
  function renderGroups(){const{g}=layers();g.innerHTML='';(A.view()?.groups||[]).forEach(group=>{const el=document.createElement('div');el.className='subject-area';el.dataset.groupId=group.id;el.style.setProperty('--group-color',group.color||'#8b5cf6');el.innerHTML=`<span class="subject-area-label">${E.escapeHtml(group.name)}</span>`;el.onclick=e=>{e.stopPropagation();E.selectedIds.clear();group.tableIds.forEach(id=>E.selectedIds.add(id));E.refreshSelection()};el.oncontextmenu=e=>{e.preventDefault();e.stopPropagation();deleteGroup(group.id)};g.appendChild(el);});A.updateGroupBounds();}

  function changeTableColor(id=E.primarySelectedId()){const t=E.findTable(id);if(!t)return alert('테이블을 선택하세요.');const color=prompt('테이블 강조 색상 (빈 값 = 기본)',t.color||'#38bdf8');if(color===null)return;A.mutate('테이블 색상 변경',()=>t.color=color.trim());}
  function applyColors(){A.view()?.tables?.forEach(t=>{const card=document.getElementById(`card-${E.tableId(t)}`)||A.getDetachedCard?.(E.tableId(t));if(!card)return;const name=card.querySelector('.table-name');if(t.color){card.dataset.customColor='true';card.style.setProperty('--custom-table-color',t.color);if(name)name.style.color=t.color}else{delete card.dataset.customColor;card.style.removeProperty('--custom-table-color');if(name)name.style.removeProperty('color')}});}
  A.renderCanvasExtras=()=>{renderGroups();renderNotes();applyColors();};A.applyTableColors=applyColors;

  function focus(ids,rels=[]){const set=new Set(ids),keys=new Set(rels.map(A.relationKey));document.querySelectorAll('.table-card').forEach(c=>{const id=c.id.replace(/^card-/,'');c.classList.toggle('analysis-focus',set.has(id));c.classList.toggle('analysis-dimmed',!set.has(id))});const all=A.view()?.relations||[];document.querySelectorAll('.connection-line').forEach(p=>{const r=all[Number(p.dataset.relationIndex)],on=r&&keys.has(A.relationKey(r));p.classList.toggle('highlighted',on);p.classList.toggle('dimmed',rels.length>0&&!on)});}
  function transactionScopeGuide(){const start=E.primarySelectedId();if(!start)return alert('기준 테이블을 선택하세요.');const view=A.view(),graph=new Map(view.tables.map(t=>[E.tableId(t),[]]));(view.relations||[]).forEach(r=>{graph.get(r.from)?.push({id:r.to,rel:r});graph.get(r.to)?.push({id:r.from,rel:r})});const dist=new Map([[start,0]]),q=[start],rels=new Map();while(q.length){const id=q.shift(),d=dist.get(id);if(d>=2)continue;for(const edge of graph.get(id)||[]){rels.set(A.relationKey(edge.rel),edge.rel);if(!dist.has(edge.id)){dist.set(edge.id,d+1);q.push(edge.id)}}}const ids=[...dist.keys()];focus(ids,[...rels.values()]);const tree=[...dist.entries()].sort((a,b)=>a[1]-b[1]).map(([id,d])=>`${'  '.repeat(d)}${d===0?'●':'└'} ${id} (depth ${d})`).join('\n');E.showOutput('Transaction Scope Guide',`기준: ${start}\n관계 2-hop 범위: ${ids.length}개 테이블\n\n${tree}\n\n※ ERD 관계만으로 추론한 후보 범위입니다. 실제 트랜잭션 경계는 서비스 로직과 함께 확인하세요.`);}

  document.getElementById('table-editor-form')?.addEventListener('submit',()=>{const edit=document.getElementById('table-editor-title')?.textContent?.includes('편집'),oldId=edit?E.primarySelectedId():null,next=A.normalizeName(document.getElementById('table-name-input')?.value);if(!oldId||!next||oldId===next)return;setTimeout(()=>{let changed=false;(A.view()?.groups||[]).forEach(g=>g.tableIds=g.tableIds.map(id=>{if(id===oldId){changed=true;return next}return id}));if(changed){E.persist();renderGroups()}},0)},true);
  Object.assign(window,{addNoteAt,createSubjectArea,changeTableColor,transactionScopeGuide});
})();
