import { SchemaView } from '../types/schema';

type Dialect = 'mysql' | 'postgresql' | 'oracle';

function typeMap(type: string, dialect: Dialect): string {
  const upper = type.toUpperCase();
  if (dialect === 'mysql') {
    if (upper.includes('VARCHAR2')) return upper.replace('VARCHAR2', 'VARCHAR');
    if (upper.includes('NUMBER')) return upper.replace('NUMBER', 'DECIMAL');
    if (upper === 'DATE') return 'DATETIME';
    return upper;
  }
  if (dialect === 'postgresql') {
    if (upper.includes('VARCHAR2')) return upper.replace('VARCHAR2', 'VARCHAR');
    if (upper.includes('NUMBER')) return upper.replace('NUMBER', 'NUMERIC');
    return upper;
  }
  return upper;
}

export function generateSQL(view: SchemaView, dialect: Dialect = 'mysql'): string {
  let sql = `-- Generated by ERD Studio\n-- Dialect: ${dialect.toUpperCase()}\n\n`;

  view.tables.forEach(table => {
    sql += `CREATE TABLE ${table.name} (\n`;

    const colDefs = table.columns.map(col => {
      let def = `  ${col.name} ${typeMap(col.type, dialect)}`;
      if (!col.nullable && !col.pk) def += ' NOT NULL';
      return def;
    });

    const pkCols = table.columns.filter(c => c.pk).map(c => c.name);
    if (pkCols.length > 0) {
      colDefs.push(`  PRIMARY KEY (${pkCols.join(', ')})`);
    }

    sql += colDefs.join(',\n');
    sql += `\n);\n\n`;
  });

  // Foreign keys
  view.relations.forEach(rel => {
    const fromTable = view.tables.find(t => t.id === rel.from);
    const toTable = view.tables.find(t => t.id === rel.to);
    if (!fromTable || !toTable) return;

    const fromCol = Array.isArray(rel.fromCol) ? rel.fromCol[0] : rel.fromCol;
    const toCol = Array.isArray(rel.toCol) ? rel.toCol[0] : rel.toCol;

    sql += `ALTER TABLE ${fromTable.name} ADD CONSTRAINT fk_${fromTable.name}_${toTable.name}_${fromCol}\n`;
    sql += `  FOREIGN KEY (${fromCol}) REFERENCES ${toTable.name}(${toCol});\n\n`;
  });

  return sql;
}
